# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  mydate: $(Get-Date -Format yyyyMMddhhmmss)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Unit Test $(buildConfiguration)'
  inputs:
    command: 'test'
    projects: '**/RomanConverterWebApi.IntegrationTest.csproj'
    testRunTitle: 'unit tests'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop $(mydate)'
    publishLocation: 'pipeline'