# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'jynsimcorpdockerregistry'
  acrRegistryServiceConnection: 'jynappacr01'
  imageRepository: 'RomanConverterWebApi'
  containerRegistry: 'jynappacr01.azurecr.io'
  dockerfilePath: 'RomanConverterWebApi/Dockerfile'
  tag: '$(Build.BuildId)'
  deploymentFile: 'deployment.yaml'

jobs:
  - job: build
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(acrRegistryServiceConnection)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(containerRegistry)/$(imageRepository):${{github.run_number}}
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)/RomanConverterWebApi
        tags: |
          $(tag)